version: '3.8'

services:
  web:
    build: .
    container_name: travel_blog_ci_web
    ports:
      - "5001:80"  
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html  
  db:
    image: mysql:5.7
    container_name: travel_blog_ci_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data_ci:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: travel_blog_ci_adminer
    restart: always
    ports:
      - "8081:8080"  # Avoid conflict

volumes:
  db_data_ci:
